# Generated by Django 4.2.7 on 2023-12-10 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Procesos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('subtotal', models.CharField(max_length=50, verbose_name='Subtotal')),
                ('total', models.CharField(max_length=50, verbose_name='Total')),
            ],
            options={
                'verbose_name_plural': 'Salarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_production', models.FloatField(default=0)),
                ('total_production_daily', models.FloatField(default=0)),
                ('total_production_weekly', models.FloatField(default=0)),
                ('total_production_monthly', models.FloatField(default=0)),
                ('total_production_yearly', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('description', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('repetitions', models.FloatField(verbose_name='Repeticiones')),
                ('estimated_time', models.CharField(max_length=50, verbose_name='Tiempo estimado')),
                ('pay', models.FloatField(verbose_name='Pago')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('activities_process', models.ManyToManyField(to='production.process')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'ordering': ['date'],
            },
        ),
    ]
