# Generated by Django 4.2.7 on 2023-12-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=50, verbose_name='Tipo Material')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('entrance', models.DateField(max_length=50, verbose_name='Fecha de Entrada')),
                ('stock', models.IntegerField(verbose_name='Existencias')),
            ],
            options={
                'verbose_name_plural': 'Inventarios',
                'ordering': ['material_type'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre material')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo material')),
                ('description', models.CharField(max_length=50, verbose_name='Descripcion del material')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Material')),
            ],
            options={
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
    ]
