# Generated by Django 4.2.7 on 2023-12-10 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
                ('description', models.TextField(verbose_name='Descripcion de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripcion del Servicio')),
                ('price', models.FloatField(verbose_name='Coste Unitario')),
                ('difficulty', models.CharField(max_length=20, verbose_name='Dificultad')),
                ('fk_idcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.categories', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Solicitud')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('pay', models.FloatField(verbose_name='Pago')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.services', verbose_name='Servicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
    ]
